// Code generated by "stringer -type=CrawlJobStatus"; DO NOT EDIT.

package dal

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[InProgress-1]
	_ = x[Completed-2]
}

const _CrawlJobStatus_name = "InProgressCompleted"

var _CrawlJobStatus_index = [...]uint8{0, 10, 19}

func (i CrawlJobStatus) String() string {
	i -= 1
	if i < 0 || i >= CrawlJobStatus(len(_CrawlJobStatus_index)-1) {
		return "CrawlJobStatus(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _CrawlJobStatus_name[_CrawlJobStatus_index[i]:_CrawlJobStatus_index[i+1]]
}
